### ISSUE TITLE
after script cleanup

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#23]
```
job1:
  script: 
    - echo deploy!
    - echo test! && false
    - echo cleanup!

job2:
  script: 
    - echo deploy!
    - echo test! && false
  after_script:
    - echo cleanup!
```
