### ISSUE TITLE
fix git clean flags example 

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#27]
Better example, make much more sence

```
# .gitlab-ci.yml

job:
  image: node
  variables:
    GIT_CLEAN_FLAGS: -ffdx -e .yarn-cache
  script:
    - yarn --cache-folder .yarn-cache

```
