### ISSUE TITLE
Add `retry`

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#38]
```yaml
# .gitlab-ci.yml

image: sikalabs/ci

test:
  script: '[ "$(slu random int --max 2)" == "0" ]'
  retry: 2
```
