### ISSUE TITLE
add simple rules example

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#47]
```
job:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - echo hello

run:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - echo run
```
