### ISSUE TITLE
example if && changes together

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#48]
```yaml
Build A:
  script: echo Build A ...
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_ID
      changes:
        - a/**/*


Build B:
  script: echo Build B ...
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_ID
      changes:
        - b/**/*
```
