### ISSUE TITLE
Add Kaniko build exmple (dockerless build)

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#57]
```yaml
image: sikalabs/ci

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .kaniko-cache

job:
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"},\"$CACHE_REGISTRY\":{\"username\":\"$CACHE_REGISTRY_USER\",\"password\":\"$CACHE_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context .
      --dockerfile ./Dockerfile
      --destination $CI_REGISTRY_IMAGE
      --cache=true
      --cache-dir .kaniko-cache
      --cache-repo $CI_REGISTRY_IMAGE/cache
```
