### ISSUE TITLE
own image in docker example

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#58]
```
variables:
  TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  IMAGE: $CI_REGISTRY_IMAGE:$TAG

job:
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE
 ```
