### ISSUE TITLE
Add slu chaos monkey status code

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#62]
```
test4:
  script: slu chaos-monkey random-status-code
  retry: 2

test5:
  script: slu chaos-monkey random-status-code
  retry: 2

test6:
  script: slu chaos-monkey random-status-code
  retry: 2
```
