### ISSUE TITLE
add better example for allow_failure=true

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#67]
```
stages:
  - build
  - test

build:
  stage: build
  script: sleep 5

build-experimental:
  stage: build
  script: sleep 15 && false
  allow_failure: true

test:
  stage: test
  script: echo test
  needs: 
    - build
```
