### ISSUE TITLE
better .pre & .post stages example

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#74]
```yaml
include: https://gitlab.sikademo.com/o2/gitlab-ci/-/raw/main/hello_world.gitlab-ci.yml

prepare:
  stage: .pre
  script: echo ....
```

```yaml
stages:
  - hello
  - world

hello:
  stage: hello
  script: echo Hello

world:
  stage: world
  script: echo World
```
