### ISSUE TITLE
needs in same stage

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#75]
```
test1:
  script: echo Test1!


test2:
  script: echo Test2!
  needs:
    - test1
```
