### ISSUE TITLE
simple variable expansion example

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#77]
```yaml
variables:
  TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID
  IMAGE: $CI_REGISTRY_IMAGE:$TAG
  URL: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_DOMAIN

job:
  script:
    - echo Docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - echo Docker build $IMAGE
    - echo Deploy to $URL
```
