### ISSUE TITLE
example of git tag from CI

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#78]
```yaml
job:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - slu git tag-next-calver
    - git remote set-url origin https://token:$COMMIT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git push origin `slu git get-last-calver`
  tags: [shell]
```
