### ISSUE TITLE
better example of environments

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/gitlab-ci-training#79]
```yaml
default:
  tags: [shell]

variables:
  HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_DOMAIN

deploy:
  script:
    - helm upgrade --install hello --repo https://helm.sikalabs.io hello-world --set host=$HOST --set TEXT="$CI_COMMIT_REF_NAME"
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$HOST
```
